config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  resources :benefits
  resources :visits do
    member do
      patch 'like', to: 'visits#like'
    end
  end
  resources :listings
  resources :location_reviews
  resources :locations do
    collection do
      post  :search
      get   :second_page
      post  :third_page
      post  :edit
    end
  end

  draw :madmin
  get 'locations/autocomplete', to: 'locations#autocomplete'
  get '/privacy', to: 'home#privacy'
  get '/terms', to: 'home#terms'
  get '/user_links', to: 'home#user_links'
  authenticate :user, ->(u) { u.admin? } do
    mount Sidekiq::Web => '/sidekiq'

    namespace :madmin do
      resources :impersonates do
        post :impersonate, on: :member
        post :stop_impersonating, on: :collection
      end
    end
  end

  resources :notifications, only: [:index]
  resources :announcements, only: [:index]
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  scope controller: :static do
    get :about
    get :terms
    get :privacy
    get :pricing
  end

  authenticated :user do
    root to: 'dashboard#show', as: :user_root
    # Alternate route to use if logged in users should still see public root
    # get "/dashboard", to: "dashboard#show", as: :user_root
  end

  # Public marketing homepage
  root to: 'static#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/listing.rb
class Listing < ApplicationRecord
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :set_listing, only: %i[ show edit update destroy ]

  # GET /listings or /listings.json
  def index
    @listings = Listing.all
  end

  # GET /listings/1 or /listings/1.json
  def show
  end

  # GET /listings/new
  def new
    @listing = Listing.new
  end

  # GET /listings/1/edit
  def edit
  end

  # POST /listings or /listings.json
  def create
    @listing = Listing.new(listing_params)

    respond_to do |format|
      if @listing.save
        format.html { redirect_to listing_url(@listing), notice: "Listing was successfully created." }
        format.json { render :show, status: :created, location: @listing }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /listings/1 or /listings/1.json
  def update
    respond_to do |format|
      if @listing.update(listing_params)
        format.html { redirect_to listing_url(@listing), notice: "Listing was successfully updated." }
        format.json { render :show, status: :ok, location: @listing }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /listings/1 or /listings/1.json
  def destroy
    @listing.destroy

    respond_to do |format|
      format.html { redirect_to listings_url, notice: "Listing was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_listing
      @listing = Listing.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def listing_params
      params.require(:listing).permit(:address_line1, :address_line2, :city, :state, :postal_code, :country, :lat, :lng)
    end
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/views/listings/_form.html.erb
<%= form_with(model: listing) do |form| %>
  <% if listing.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(listing.errors.count, "error") %> prohibited this listing from being saved:</h2>

      <ul>
      <% listing.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="sm:col-span-6">
    <label for="title" class="block text-sm font-medium text-gray-700">
      Title
    </label>
    <div class="mt-1">
      <input type="text" name="listing[title]" id="title" value="<%= @listing.title %>" class="shadow-sm focus:ring-indigo-500 focus:border-indigo-500 block w-full sm:text-sm border-gray-300 rounded-md">
    </div>
  </div>
  <!-- Yes, the data-action with map-loaded is convoluted.  For explanation, see https://youtu.be/Zj15TCNtxKE?t=1057 -->
  <div data-controller="address" data-action="map-loaded@window->address#initGoogle" class="sm:col-span-6">
      <label for="address" class="block text-sm font-medium text-gray-700">
      Address
    </label>
    <input type="text" id="address" data-address-target="input" autocomplete="off" class="shadow-sm focus:ring-indigo-500 focus:border-indigo-500 block w-full sm:text-sm border-gray-300 rounded-md">

    <input type="hidden" name="listing[address_line1]" data-address-target="line1">
    <input type="hidden" name="listing[address_line2]" data-address-target="line2">
    <input type="hidden" name="listing[city]" data-address-target="city">
    <input type="hidden" name="listing[state]" data-address-target="state">
    <input type="hidden" name="listing[postal_code]" data-address-target="postal_code">
    <input type="hidden" name="listing[country]" data-address-target="country">
    <input type="hidden" name="listing[lat]" data-address-target="lat">
    <input type="hidden" name="listing[lng]" data-address-target="lng">
  </div>

  <div class="mb-3">
    <% if listing.persisted? %>
      <div class="float-end">
        <%= link_to 'Destroy', listing, method: :delete, class: "text-danger", data: { confirm: 'Are you sure?' } %>
      </div>
    <% end %>

    <input type="submit" value="Create listing" class="w-full flex justify-center py-2 px-4 border border-transparent rounded-md shadow-sm text-sm font-medium text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">

    <% if listing.persisted? %>
    <%= link_to "Cancel", listing_path(listing), class: "bg-red-500 hover:bg-red-700 text-white p-2 rounded" %>
    <% else %>
    <%= link_to "Cancel", listings_path, class: "bg-red-500 hover:bg-red-700 text-white p-2 rounded" %>
    <% end %>  </div>
  
<% end %>

app/views/listings/_listing.html.erb
<div id="<%= dom_id listing %>">
  <strong>  <%= listing.title %></strong> <br>
  Address line1:  <%= listing.address_line1 %>

  Address line2: <%= listing.address_line2 %> <br> 
  City: <%= listing.city %> <br>
  State:   <%= listing.state %> <br>
  
  Postal code:  <%= listing.postal_code %> <br>
  Country:   <%= listing.country %> <br>
  Lat:  <%= listing.lat %> <br>
  Lng:  <%= listing.lng %> br
</div>
<hr>&nbsp;
<%= link_to new_listing_path,  class: 'btn btn-primary', data:  {turbo_frame: "app-modal"} do %>
Add New Listing
<% end %>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
<%= link_to listing,  class: 'btn btn-primary', data:  {turbo_frame: "app-modal"} do %>
Show
<% end %>

<hr>

app/views/listings/_results.html.erb
    <div class="flex" data-controller="listing-map" data-action="map-loaded@window->address#initGoogle" >
      <div class="w-1/2 p-4 overflow-auto" style="height: 500px;">
        <ul class="list-none">
          <% @listings.each do |listing| %>
          <li class="border border-gray-400 mb-4 p-4 rounded-lg shadow-lg"  data-lat="<%= listing.lat %>" data-title="<%= listing.title %>" data-lng="<%= listing.lng %>">
            <a href="<%= listing_path(listing) %>" class="group block w-full aspect-w-10 aspect-h-7 rounded-lg bg-gray-100 focus-within:ring-2 focus-within:ring-offset-2 focus-within:ring-offset-gray-100 focus-within:ring-indigo-500 overflow-hidden">
              <!-- <img src="https://images.unsplash.com/photo-1582053433976-25c00369fc93?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=512&q=80" alt="" class="object-cover pointer-events-none group-hover:opacity-75"> -->
              <button type="button" class="absolute inset-0 focus:outline-none">
                <span class="sr-only">View details for <%= listing.title %></span>
              </button>
              <h3 class="font-bold mb-2"><%= listing.title %></h3>
              <p class="mb-2"><%= listing.address_line1 %></p>
              <p class="mb-2"><%= listing.city %></p>
              <p class="mb-2"><%= listing.state %></p>
    
            </a>
            <div class="flex items-center">
              <i class="fas fa-star text-yellow-500 mr-1"></i>
              <i class="fas fa-star text-yellow-500 mr-1"></i>
              <i class="fas fa-star text-yellow-500 mr-1"></i>
              <i class="fas fa-star text-yellow-500 mr-1"></i>
              <i class="fas fa-star text-gray-500"></i>
            </div>
          </li>
          <% end %>
        </ul>
      </div>
      <div class="w-1/2 p-4">
        <h2>howdy</h2>
        <%= js_map [{latitude: 37.7829, longitude: -122.4190}] %>
        <!-- <div data-listing-map-target="map"class="bg-gray-300 h-64" style="height: 500px; width: 100%;"></div> -->
      </div>
    </div>
                        

app/views/listings/edit.html.erb
<h1>Edit Listing</h1>

<%= render 'form', listing: @listing %>

app/views/listings/index.html.erb
<style>
  		.super-container {
			margin: 0;
			padding: 0;
			display: grid;
			grid-template-columns: 1fr;
			grid-template-rows: 1fr;
		}

		#content-container {
			position: absolute;
			top: 0;
			left: 0;
			width: 25%;
			height: 100%;
			display: grid;
			grid-template-rows: auto 1fr;
			grid-template-areas: "header" "content";
			z-index: 2;
			background: rgba(255, 255, 255, 0.8);
			overflow-y: auto;
		}

		header {
			grid-area: header;
			padding: 20px;
			background: #333;
			color: #fff;
			font-size: 24px;
			font-weight: bold;
			text-align: center;
		}

		#content {
			grid-area: content;
			padding: 20px;
		}

		#image {
			position: absolute;
			top: 0;
			left: 0;
			width: 100%;
			height: 100%;
			z-index: 1;
			background: url('https://source.unsplash.com/random/1920x1080');
			background-size: cover;
			background-position: center;
		}

		@media screen and (max-width: 768px) {
			#content-container {
				position: relative;
				width: 100%;
				height: auto;
				grid-template-areas: "header" "content";
				overflow-y: visible;
			}
		}
</style>

<div class="super-container">
  <div id="content-container">
      <header>
		<div class="locations">
			<% @listings.each do |listing| %>
			  <%= render "listing", listing: listing %>
			<% end %>
			  <%#= render "location", location: location %>
		  </div>
	  </header>
      <div id="content">
        <p>Local content here...</p>
      </div>
    </div>
    <div id="image"></div>
    
  </div>
  

app/views/listings/new.html.erb
<%= turbo_frame_tag "app-modal" do %>
    <div class="app-modal">
    <h1>New listing</h1>

    <%= render 'form', listing: @listing %>

    <div class="back">
        <%= link_to "Cancel",
                     "#",
                     data: {controller: "modals", action: "modals#close"},
                     class: "cancel-button" %>
                     
    </div>
    
    </div>

<% end %>

app/views/listings/show.html.erb
<%= turbo_frame_tag "app-modal" do %>

    <div class="app-modal bg-orange-200">

      <div class="back">
        <%= link_to "Cancel",
                     "#",
                     data: {controller: "modals", action: "modals#close"},
                     class: "cancel-button" %>
                     
      </div>
      
<div class="page-header">
  <%= link_to listings_path, class: 'btn btn-default' do %>
    All Listings
  <% end %>
  <%= link_to edit_listing_path(@listing), class: 'btn btn-primary' do %>
    Edit
  <% end %>
  <h1>Show listing</h1>
</div>

<dl class="dl-horizontal">
  <dt>Address line1:</dt>
  <dd><%= @listing.address_line1 %></dd>
  <dt>Address line2:</dt>
  <dd><%= @listing.address_line2 %></dd>
  <dt>City:</dt>
  <dd><%= @listing.city %></dd>
  <dt>State:</dt>
  <dd><%= @listing.state %></dd>
  <dt>Postal code:</dt>
  <dd><%= @listing.postal_code %></dd>
  <dt>Country:</dt>
  <dd><%= @listing.country %></dd>
  <dt>Lat:</dt>
  <dd><%= @listing.lat %></dd>
  <dt>Lng:</dt>
  <dd><%= @listing.lng %></dd>
</dl>
</div>

<% end %>