config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  resources :benefits
  resources :visits do
    member do
      patch 'like', to: 'visits#like'
    end
  end
  resources :listings
  resources :location_reviews
  resources :locations do
    collection do
      post  :search
      get   :second_page
      post  :third_page
      post  :edit
    end
  end

  draw :madmin
  get 'locations/autocomplete', to: 'locations#autocomplete'
  get '/privacy', to: 'home#privacy'
  get '/terms', to: 'home#terms'
  get '/user_links', to: 'home#user_links'
  authenticate :user, ->(u) { u.admin? } do
    mount Sidekiq::Web => '/sidekiq'

    namespace :madmin do
      resources :impersonates do
        post :impersonate, on: :member
        post :stop_impersonating, on: :collection
      end
    end
  end

  resources :notifications, only: [:index]
  resources :announcements, only: [:index]
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  scope controller: :static do
    get :about
    get :terms
    get :privacy
    get :pricing
  end

  authenticated :user do
    root to: 'dashboard#show', as: :user_root
    # Alternate route to use if logged in users should still see public root
    # get "/dashboard", to: "dashboard#show", as: :user_root
  end

  # Public marketing homepage
  root to: 'static#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/visit.rb
class Visit < ApplicationRecord
  belongs_to :user
  belongs_to :location, dependent: :destroy
  #   has_many :votes, as: :votable

  #   validates :user, presence: true
  validates :location, presence: true
  # validates :comment, presence: true

  acts_as_votable

  #    # upvote or remove vote
  #   def upvote!(user)
  #     if user.voted_up_on? self, vote_scope: 'like'
  #       unvote_by user, vote_scope: 'like'
  #     else
  #       upvote_by user, vote_scope: 'like'
  #     end
  #   end

  #   # downvote or remove vote
  #   def downvote!(user)
  #     if user.voted_down_on? self, vote_scope: 'like'
  #       unvote_by user, vote_scope: 'like'
  #     else
  #       downvote_by user, vote_scope: 'like'
  #     end
  #   end

  #   def vote!(vote_type, user)
  #     case vote_type
  #       when 'upvote'
  #         self.upvote! user
  #       when 'downvote'
  #         self.downvote! user
  #     end
  #   end
end

app/controllers/visits_controller.rb
class VisitsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_visit, only: %i[show edit update destroy]

  # GET /visits or /visits.json
  def index
    @visits = Visit.all.order(created_at: :desc).first(10)
  end

  # GET /visits/1 or /visits/1.json
  def show; end

  # GET /visits/new
  def new
    @visit = Visit.new
  end

  # GET /visits/1/edit
  def edit; end

  # POST /visits or /visits.json
  # def create
  #   @visit = current_user.visits.new(visit_params)

  #   respond_to do |format|
  #     if @visit.save
  #       format.html { redirect_to visit_url(@visit), notice: 'Visit was successfully created.' }
  #       format.json { render :show, status: :created, location: @visit }
  #       format.turbo_stream do
  #         render turbo_stream: turbo_stream.prepend(
  #           :visits,
  #           partial: 'visits/visit',
  #           locals: { visit: @visit }
  #         )
  #       end

  #     else
  #       format.html { render :new, status: :unprocessable_entity }
  #       format.json { render json: @visit.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end
  ###
  # POST /visits or /visits.json
  def create
    return unless %w[upvote downvote].include?(visit_params[:vote_type])
    return if visit_params[:location_id].blank?

    # @location = Location.find(params[:location_id])
    # @location = Location.find(visit_params[:location_id]) || Location.last
    # @visit = @location.visits.create!(location: @location, user: current_user)
    @visit = current_user.visits.new(
      location_id: visit_params[:location_id],
      comment: visit_params[:comment]
    )

    respond_to do |format|
      if @visit.save!
        # @visit.vote!(visit_params[:vote_type], current_user)
        @visit.vote_by voter: current_user, vote: visit_params[:vote_type]
        format.html { redirect_to visit_url(@visit), notice: 'Visit was successfully created.' }
        format.json { render :show, status: :created, location: @visit }
        format.turbo_stream do
          render turbo_stream: turbo_stream.prepend(
            :visits,
            partial: 'visits/visit',
            locals: { visit: @visit }
          )
        end
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @visit.errors, status: :unprocessable_entity }
      end
    end
  end

  ###
  # PATCH/PUT /visits/1 or /visits/1.json
  def update
    respond_to do |format|
      if @visit.update(visit_params)
        format.html { redirect_to visit_url(@visit), notice: 'Visit was successfully updated.' }
        format.json { render :show, status: :ok, location: @visit }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @visit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /visits/1 or /visits/1.json
  def destroy
    @visit.destroy

    respond_to do |format|
      format.html { redirect_to visits_url, notice: 'Visit was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_visit
    @visit = Visit.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def visit_params
    params.require(:visit).permit(:comment, :user_id, :location_id, :vote_type)
  end
end

app/helpers/visits_helper.rb
module VisitsHelper
end

app/views/visits/_create_successful.html.erb
<div class="content text-black">
    <div class="flex justify-between">
      <button class="close btn button-primary" data-action="click->visit-dialog#closeDialog">
        <i class="fas fa-times fa-lg"></i>&nbsp;&nbsp; Done
      </button>
    </div>
</div>
<!-- sumission successful -->
<div class="alert alert-success">
  <strong>Thank you!</strong> People rely on your experience.
</div>

app/views/visits/_form.copy.erb
<%= form_with(model: visit) do |form| %>
  <% if visit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(visit.errors.count, "error") %> prohibited this visit from being saved:</h2>

      <ul>
      <% visit.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label :comment, class: 'form-label' %>
      <%= form.text_area :comment, class: 'form-control' %>
    </div>


      <%= form.hidden_field :location_id, value: params[:location_id]|| Location.last.id %>

  <div class="mb-3">
    <% if visit.persisted? %>
      <div class="float-end">
        <%= link_to 'Destroy', visit, method: :delete, class: "text-danger", data: { confirm: 'Are you sure?' } %>
      </div>
    <% end %>

    <%= form.submit class: 'btn btn-primary' %>

    <% if visit.persisted? %>
      <%= link_to "Cancel", visit, class: "btn btn-link" %>
    <% else %>
      <%= link_to "Cancel", visits_path, class: "btn btn-link" %>
    <% end %>
  </div>
<% end %>

app/views/visits/_form.html.erb
  <%= form_with(model: visit) do |form| %>
    <% if visit.errors.any? %>
      <div class="alert alert-error">
        <h2><%= pluralize(visit.errors.count, "error") %> prohibited this visit from being saved:</h2>
        <ul>
        <% visit.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <%= form.hidden_field :location_id, value: params[:location_id] %>

      <div class="form-group mb-6">
        <%= form.label :vote_type, "Vote Type" %><br>
        <div class="flex items-center">
          <div class="upvote mr-4">
            <%= form.radio_button :vote_type, "upvote" %>
            <%= form.label :vote_type_upvote do%>
              <i class="fas fa-thumbs-up fa-2x fa-lg"></i>
            <% end %>
          </div>
          <div class="downvote mr-4">
            <%= form.radio_button :vote_type, "downvote" %>
            <%= form.label :vote_type_downvote do %>
              <i class="fas fa-thumbs-down fa-2x fa-lg"></i>
            <% end %>  
          </div>
          <div class="phrase text-black border">
            What was your overall experience?
          </div>
        </div>
      </div>
      <div class="form-group mb-6">
        <%= form.label :comment, "Comment" %>
        <%= form.text_area :comment, class: "form-control bg-white border-2 border-gray-300 rounded-md px-4 py-2 outline-4" %>
      </div>
    <div class="mb-6">
      <% if visit.persisted? %>
        <div class="float-right">
          <%= link_to 'Destroy', visit, method: :delete, class: "text-red-600 hover:text-red-800", data: { confirm: 'Are you sure?' } %>
        </div>
      <% end %>

      <%= form.submit class: 'button button-primary rounded-md px-4 py-2 mr-2 bg-blue-700 text-white',
                      value: 'Share your vote'
      %>

      <% if visit.persisted? %>
        <%#= link_to "Cancel", visit, class: "button button-secondary" %>
        <%= link_to "#", 
                    class:  "p-2 text-blue-500",
                    data: {controller: "modals", action: "modals#close"} do %>
          Cancel
        <% end %>
      <% else %>
        <%#= link_to "Cancel", visits_path, class: "button button-secondary" %>
        <%= link_to "#", 
                    class:  "p-2 text-blue-500",
                    data: {controller: "modals", action: "modals#close"} do %>
          Cancel
        <% end %>

      <% end %>
    </div>
  <% end %>

app/views/visits/_visit.html.erb
<div id="<%= dom_id visit %>" class="border-b-4 border-gray-500">
  <p>
    <strong>Comment:</strong>
    <%= visit.comment %>
  </p>

  <p>
    <strong>User:</strong>
    <%= visit.user_id %>
  </p>

  <p>
    <strong>Location:</strong>
    <%= visit.location_id %>
  </p>

  <p>
    upvotes: <%= visit.votes_for.up.count%>
  </p>
  <p>
    downvotes: <%= visit.votes_for.down.count%>
  </p>
</div>

app/views/visits/_visit_modal.html.erb
<div class="success bg-blue-800">
    <h1>you did it!</h1>
    <div class="back">
        <%= link_to "Cancel",
                     "#",
                     data: {controller: "modals", action: "modals#close"},
                     class: "cancel-button" %>
    </div>
    <div class="page-header">
        <h1>Success</h1>
    </div>
</div>

app/views/visits/create.turbo_stream.erb
<%= turbo_stream.update "modal" do %>
  <%= render "create_successful" %>
  <p>super Lorem ipsum dolor sit amet consectetur adipisicing elit. Sunt accusantium optio architecto fugiat ad quisquam ipsam dolor sit. Excepturi, explicabo voluptates. Sunt neque laborum reiciendis at sapiente aspernatur sit alias?</p>
<% end %>

app/views/visits/edit.html.erb
<h1>Edit Visit</h1>

<%= render 'form', visit: @visit %>

app/views/visits/index.html.erb
<div class="row">
  <div class="col-sm-6">
    <h1>Visits</h1>
  </div>

  <div class="col-sm-6 text-end">
    <!-- modal: visit start -->    
  <%= link_to new_visit_path, data: {turbo_frame: "modal"}, class: 'btn btn-primary' do %>
    Add New Visit
  <% end %>
    <!-- modal: visit finish -->
  
  </div>
</div>

<h2>Visits</h2>
  <div id="visits">
      <% @visits.each do |visit| %>
        <%= render visit %>
      <% end %>

  </div>
<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
    

            <th>ID</th>
            <th>Comment</th>
            <th>User</th>
            <th>Location</th>
            
          <th></th>
        
      </tr>
    </thead>

    <tbody>
      <% @visits.each do |visit| %>
        <%= content_tag :tr, id: dom_id(visit), class: dom_class(visit) do %>
          

                      <td><%= visit.id %></td>
                      <td><%= visit.comment %></td>
                      <td><%= visit.user_id %></td>
                      <td><%= visit.location_id %></td>
          
          
            <td><%= link_to 'Show', visit %></td>
          
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/visits/new.html.erb
    <!-- modal: visit start -->
    <% @location = Location.find(params[:location_id]) %>
    <%= turbo_frame_tag "modal" do %>
        <div data-controller="turbomodal" data-action="turbo:submit-end->turbomodal#submitEnd" class="location-detail-modal">
<!--  -->
                <!-- HTML code for the dialog -->
                <div class="fixed inset-0 bg-gray-300 bg-opacity-75">
                        <div class="bg-gray-300 rounded-lg w-full md:w-1/2 mx-auto h-screen">
                                <header class="flex justify-between items-center py-4 px-6 bg-gray100 text-black">
                                        <div class="flex-shrink-0">
                                                <a href="#" class="text-blue-700 hover:text-blue-500">Cancel</a>
                                        </div>
                                        <div class="flex flex-col justify-center items-center">
                                                <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6 text-gray-300" viewBox="0 0 20 20" fill="bg-green-700">
                                                <path fill-rule="evenodd" d="M10 0a10 10 0 1 0 10 10A10 10 0 0 0 10 0zm5.218 10.898l-4.98 4.98c-.195.195-.452.293-.708.293-.256 0-.513-.098-.708-.293l-4.98-4.98a.999.999 0 1 1 1.414-1.414L10 12.586l4.804-4.804a.999.999 0 1 1 1.414 1.414z" />
                                                </svg>
                                                <h1 class="text-lg font-bold text-center mb-1"><%= @location.name %></h1>
                                        </div>
                                        <div class="flex-shrink-0">
                                                <a href="#" class="text-blue-700 hover:text-blue-500">Done</a>
                                        </div>
                                </header>
                                <%= render 'form', visit: @visit %>
                                <footer class="flex justify-end py-4 px-6  text-black">
                                        <p>Ratings and photos are associated with your membership account.  By contributing, you agree to the Terms.</p>
                                </footer>            
                        </div>
                </div>
<!--  -->
        </div>

<% end %>
    <!-- modal: visit finish -->

app/views/visits/show.html.erb
<div class="page-header">
  <%= link_to visits_path, class: 'btn btn-default' do %>
    All Visits
  <% end %>
  <%= link_to edit_visit_path(@visit), class: 'btn btn-primary' do %>
    Edit
  <% end %>
  <h1>Show visit</h1>
</div>

<dl class="dl-horizontal">
  <dt>Comment:</dt>
  <dd><%= @visit.comment %></dd>
  <dt>User:</dt>
  <dd><%= @visit.user_id %></dd>
  <dt>Location:</dt>
  <dd><%= @visit.location_id %></dd>
</dl>