config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  resources :benefits
  resources :visits do
    member do
      patch 'like', to: 'visits#like'
    end
  end
  resources :listings
  resources :location_reviews
  resources :locations do
    collection do
      post  :search
      get   :second_page
      post  :third_page
      post  :edit
    end
  end

  draw :madmin
  get 'locations/autocomplete', to: 'locations#autocomplete'
  get '/privacy', to: 'home#privacy'
  get '/terms', to: 'home#terms'
  get '/user_links', to: 'home#user_links'
  authenticate :user, ->(u) { u.admin? } do
    mount Sidekiq::Web => '/sidekiq'

    namespace :madmin do
      resources :impersonates do
        post :impersonate, on: :member
        post :stop_impersonating, on: :collection
      end
    end
  end

  resources :notifications, only: [:index]
  resources :announcements, only: [:index]
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  scope controller: :static do
    get :about
    get :terms
    get :privacy
    get :pricing
  end

  authenticated :user do
    root to: 'dashboard#show', as: :user_root
    # Alternate route to use if logged in users should still see public root
    # get "/dashboard", to: "dashboard#show", as: :user_root
  end

  # Public marketing homepage
  root to: 'static#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/controllers/location_reviews_controller.rb
class LocationReviewsController < ApplicationController
  before_action :set_location_review, only: %i[ show edit update destroy ]

  # GET /location_reviews or /location_reviews.json
  def index
    @location_reviews = LocationReview.all
  end

  # GET /location_reviews/1 or /location_reviews/1.json
  def show
  end

  # GET /location_reviews/new
  def new
    @location_review = LocationReview.new
  end

  # GET /location_reviews/1/edit
  def edit
  end

  # POST /location_reviews or /location_reviews.json
  def create
    @location = Location.find(params[:location_id]) 
    @location_review = @location.location_reviews.build(location_review_params)

    respond_to do |format|
      if @location_review.save
        format.html { redirect_to location_url(@location), notice: "Thanks for your help!  Location review was successfully created." }
        format.json { render :show, status: :created, location: @location_review }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @location_review.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /location_reviews/1 or /location_reviews/1.json
  def update
    respond_to do |format|
      if @location_review.update(location_review_params)
        format.html { redirect_to location_review_url(@location_review), notice: "Location review was successfully updated." }
        format.json { render :show, status: :ok, location: @location_review }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @location_review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /location_reviews/1 or /location_reviews/1.json
  def destroy
    @location_review.destroy

    respond_to do |format|
      format.html { redirect_to location_reviews_url, notice: "Location review was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_location_review
      @location_review = LocationReview.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def location_review_params
      params.require(:location_review).permit(:author_name, 
                                              :author_url, 
                                              :profile_url, 
                                              :rating, 
                                              :text, 
                                              :time, 
                                              :type, 
                                              :location_id)
    end
end

app/helpers/location_reviews_helper.rb
module LocationReviewsHelper
end

app/views/location_reviews/_form.html.erb
<%= form_with(model: location_review) do |form| %>
  <% if location_review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(location_review.errors.count, "error") %> prohibited this location_review from being saved:</h2>

      <ul>
      <% location_review.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label :author_name, class: 'form-label' %>
      <%= form.text_field :author_name, class: 'form-control' %>
    </div>

  <div class="mb-3">
    <%= form.label :author_url, class: 'form-label' %>
      <%= form.text_field :author_url, class: 'form-control' %>
    </div>

  <div class="mb-3">
    <%= form.label :profile_url, class: 'form-label' %>
      <%= form.text_field :profile_url, class: 'form-control' %>
    </div>

  <div class="mb-3">
    <%= form.label :rating, class: 'form-label' %>
      <%= form.number_field :rating, class: 'form-control' %>
    </div>

  <div class="mb-3">
    <%= form.label :text, class: 'form-label' %>
      <%= form.text_field :text, class: 'form-control' %>
    </div>

  <div class="mb-3">
    <%= form.label :time, class: 'form-label' %>
      <%= form.number_field :time, class: 'form-control' %>
    </div>

  <div class="mb-3">
    <%= form.label :type, class: 'form-label' %>
      <%= form.text_field :type, class: 'form-control' %>
    </div>

  <div class="mb-3">
    <%= form.label :location_id, class: 'form-label' %>
      <%= form.text_field :location_id, class: 'form-control' %>
    </div>

  <div class="mb-3">
    <% if location_review.persisted? %>
      <div class="float-end">
        <%= link_to 'Destroy', location_review, method: :delete, class: "text-danger", data: { confirm: 'Are you sure?' } %>
      </div>
    <% end %>

    <%= form.submit class: 'btn btn-primary' %>

    <% if location_review.persisted? %>
      <%= link_to "Cancel", location_review, class: "btn btn-link" %>
    <% else %>
      <%= link_to "Cancel", location_reviews_path, class: "btn btn-link" %>
    <% end %>
  </div>
<% end %>

app/views/location_reviews/_location_review.html.erb
<div id="<%= dom_id location_review %>">
  <p>
    <strong>Author name:</strong>
    <%= location_review.author_name %>
  </p>

  <p>
    <strong>Author url:</strong>
    <%= location_review.author_url %>
  </p>

  <p>
    <strong>Profile url:</strong>
    <%= location_review.profile_url %>
  </p>

  <p>
    <strong>Rating:</strong>
    <%= location_review.rating %>
  </p>

  <p>
    <strong>Text:</strong>
    <%= location_review.text %>
  </p>

  <p>
    <strong>Time:</strong>
    <%= location_review.time %>
  </p>

  <p>
    <strong>Type:</strong>
    <%= location_review.type %>
  </p>

  <p>
    <strong>Location:</strong>
    <%= location_review.location_id %>
  </p>

</div>

app/views/location_reviews/edit.html.erb
<h1>Edit Location_review</h1>

<%= render 'form', location_review: @location_review %>

app/views/location_reviews/index.html.erb
<div class="row">
  <div class="col-sm-6">
    <h1>Location_reviews</h1>
  </div>

  <div class="col-sm-6 text-end">
  <%= link_to new_location_review_path, class: 'btn btn-primary' do %>
    Add New Location review
  <% end %>
  </div>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
    

            <th>Author name</th>
            <th>Author url</th>
            <th>Profile url</th>
            <th>Rating</th>
            <th>Text</th>
            <th>Time</th>
            <th>Type</th>
            <th>Location</th>
            
          <th></th>
        
      </tr>
    </thead>

    <tbody>
      <% @location_reviews.each do |location_review| %>
        <%= content_tag :tr, id: dom_id(location_review), class: dom_class(location_review) do %>
          

                      <td><%= location_review.author_name %></td>
                      <td><%= location_review.author_url %></td>
                      <td><%= location_review.profile_url %></td>
                      <td><%= location_review.rating %></td>
                      <td><%= location_review.text %></td>
                      <td><%= location_review.time %></td>
                      <td><%= location_review.type %></td>
                      <td><%= location_review.location %></td>
          
          
            <td><%= link_to 'Show', location_review %></td>
          
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/location_reviews/new.html.erb
<h1>New location_review</h1>

<%= render 'form', location_review: @location_review %>

app/views/location_reviews/show.html.erb
<div class="page-header">
  <%= link_to location_reviews_path, class: 'btn btn-default' do %>
    All Location_reviews
  <% end %>
  <%= link_to edit_location_review_path(@location_review), class: 'btn btn-primary' do %>
    Edit
  <% end %>
  <h1>Show location_review</h1>
</div>

<dl class="dl-horizontal">
  <dt>Author name:</dt>
  <dd><%= @location_review.author_name %></dd>
  <dt>Author url:</dt>
  <dd><%= @location_review.author_url %></dd>
  <dt>Profile url:</dt>
  <dd><%= @location_review.profile_url %></dd>
  <dt>Rating:</dt>
  <dd><%= @location_review.rating %></dd>
  <dt>Text:</dt>
  <dd><%= @location_review.text %></dd>
  <dt>Time:</dt>
  <dd><%= @location_review.time %></dd>
  <dt>Type:</dt>
  <dd><%= @location_review.type %></dd>
  <dt>Location:</dt>
  <dd><%= @location_review.location %></dd>
</dl>